version: '3.1'
services:
  api:
    image: ghcr.io/yanmak/top-api/top-api:latest
    container_name: top-api
    restart: always
    ports:
      - '3333:3333'
    volumes:
      - ./envs:/opt/app/envs
