name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/YanMak/top-api/top-api
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tags: 'develop'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
